/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interface;

import avaliaacaorestaurante.Avaliacao;
import avaliaacaorestaurante.Restaurante;
import avaliaacaorestaurante.Usuario;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Nicopau
 */
public class TelaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form TelaPrincipal
     */
    /*NICOLAS - Usuario logado atualmente*/
    private Usuario usuarioAtual;
    /*Nicolas*/
    
    public TelaPrincipal() {
        initComponents();
        /*NICOLAS*/
        setLocationRelativeTo(null);
        /*NICOLAS - CONFIGURAÇÕES DE INIT*/
        pnlLogin.setVisible(true);
        pnlMainCadastrado.setVisible(false);
        pnlRestaurantes.setVisible(false);
        pnlMainVisitante.setVisible(false);
        pnlMinhasAvaliacoes.setVisible(false);
        pnlMeusRestaurantes.setVisible(false);
        pnlFazerAvaliacao.setVisible(false);
        /*NICOLAS*/
        
        /*NICOLAS - CRIAÇÃO DE OBJETOS TESTE*/
        Usuario usuarioTeste = new Usuario("anton", "Anton117*");
        Restaurante restauranteTeste = new Restaurante("Arab's", usuarioTeste);
        usuarioTeste.getListaAvaliacoes().add(new Avaliacao(usuarioTeste, (float) 4.7, "comida muito boa", restauranteTeste));
        /*NICOLAS*/
    }
    
    /*NIOCLAS*/
    public void carregarTblMinhasAvaliacoes(Usuario a){
        DefaultTableModel modelo = new DefaultTableModel(new Object[] {"Restaurante","Comentário","Nota"}, 0);
        ArrayList<Avaliacao> avaliacoesUsuario = a.getListaAvaliacoes();
        
        for (Avaliacao avaliacao : avaliacoesUsuario){
            Object linha[] = new Object[] {avaliacao.getRestaurante().getNome(),avaliacao.getConteudo(),avaliacao.getNota(), "--"};
            
            modelo.addRow(linha);
        }
        
        tblMinhasAvaliacoes.setModel(modelo);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlLogin = new javax.swing.JPanel();
        txtUsuarioLogin = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnCriarContaLogin = new javax.swing.JButton();
        btnAcessarLogin = new javax.swing.JButton();
        txtSenhaLogin = new javax.swing.JPasswordField();
        btnEntrarVisitante = new javax.swing.JButton();
        pnlMainCadastrado = new javax.swing.JPanel();
        btnRestaurantesMainCadastrado = new javax.swing.JButton();
        btnMinhasAvMainCadastrado = new javax.swing.JButton();
        btnSairMainCadastrado = new javax.swing.JButton();
        pnlRestaurantes = new javax.swing.JPanel();
        txtBuscaRestaurantes = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        btnBuscarRestaurantes = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblRestaurantes = new javax.swing.JTable();
        btnMeusRestaurantes = new javax.swing.JButton();
        btnFazerAvaliacao = new javax.swing.JButton();
        btnVoltarRestaurantes = new javax.swing.JButton();
        pnlMainVisitante = new javax.swing.JPanel();
        txtBuscarRestauranteVisitante = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        btnBuscarRestVisitante = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblRestauranteVisitante = new javax.swing.JTable();
        btnSairVisitante = new javax.swing.JButton();
        pnlMinhasAvaliacoes = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblMinhasAvaliacoes = new javax.swing.JTable();
        txtBuscarMinhasAvaliacoes = new javax.swing.JTextField();
        btnVoltarMinhasAvaliacoes = new javax.swing.JButton();
        btnEditarMinhasAvaliacoes = new javax.swing.JButton();
        btnSalvarMinhasAvaliacoes = new javax.swing.JButton();
        btnExcluirMinhasAvaliacoes = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        txtComentarioMinhasAvaliacoes = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtNotaMinhasAvaliacoes = new javax.swing.JTextField();
        btnBuscarMinhasAvaliacoes = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        pnlMeusRestaurantes = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tblMeusRestaurantes = new javax.swing.JTable();
        txtBuscarMeusRestaurantes = new javax.swing.JTextField();
        btnBuscarMeusRestaurantes = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        btnCriarRestaurante = new javax.swing.JButton();
        btnVoltarMeusRestaurantes = new javax.swing.JButton();
        pnlFazerAvaliacao = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        tblRestaurantesFazerAvaliacao = new javax.swing.JTable();
        txtComentarioFazerAvaliacao = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtNotaFazerAvaliacao = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        btnSalvarFazerAvaliacao = new javax.swing.JButton();
        btnVoltarFazerAvaliacao = new javax.swing.JButton();
        txtBuscarFazerAvaliacao = new javax.swing.JTextField();
        btnBuscarFazerAvaliacao = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.CardLayout());

        txtUsuarioLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUsuarioLoginActionPerformed(evt);
            }
        });

        jLabel1.setText("Usuário");

        jLabel2.setText("Senha");

        btnCriarContaLogin.setText("Criar conta");
        btnCriarContaLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCriarContaLoginActionPerformed(evt);
            }
        });

        btnAcessarLogin.setText("ACESSAR");
        btnAcessarLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAcessarLoginActionPerformed(evt);
            }
        });

        btnEntrarVisitante.setText("Entrar como visitante");
        btnEntrarVisitante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEntrarVisitanteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlLoginLayout = new javax.swing.GroupLayout(pnlLogin);
        pnlLogin.setLayout(pnlLoginLayout);
        pnlLoginLayout.setHorizontalGroup(
            pnlLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlLoginLayout.createSequentialGroup()
                .addGroup(pnlLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlLoginLayout.createSequentialGroup()
                        .addGap(367, 367, 367)
                        .addGroup(pnlLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1)
                            .addGroup(pnlLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(txtSenhaLogin, javax.swing.GroupLayout.DEFAULT_SIZE, 131, Short.MAX_VALUE)
                                .addComponent(txtUsuarioLogin, javax.swing.GroupLayout.Alignment.LEADING))))
                    .addGroup(pnlLoginLayout.createSequentialGroup()
                        .addGap(379, 379, 379)
                        .addGroup(pnlLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnCriarContaLogin)
                            .addComponent(btnAcessarLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlLoginLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnEntrarVisitante, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(389, Short.MAX_VALUE))
        );
        pnlLoginLayout.setVerticalGroup(
            pnlLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlLoginLayout.createSequentialGroup()
                .addGap(136, 136, 136)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtUsuarioLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtSenhaLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addComponent(btnCriarContaLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(75, 75, 75)
                .addComponent(btnAcessarLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49)
                .addComponent(btnEntrarVisitante, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(136, Short.MAX_VALUE))
        );

        getContentPane().add(pnlLogin, "card2");

        btnRestaurantesMainCadastrado.setText("RESTAURANTES");
        btnRestaurantesMainCadastrado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRestaurantesMainCadastradoActionPerformed(evt);
            }
        });

        btnMinhasAvMainCadastrado.setText("MINHAS AVALIAÇÕES");
        btnMinhasAvMainCadastrado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMinhasAvMainCadastradoActionPerformed(evt);
            }
        });

        btnSairMainCadastrado.setText("SAIR");
        btnSairMainCadastrado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairMainCadastradoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlMainCadastradoLayout = new javax.swing.GroupLayout(pnlMainCadastrado);
        pnlMainCadastrado.setLayout(pnlMainCadastradoLayout);
        pnlMainCadastradoLayout.setHorizontalGroup(
            pnlMainCadastradoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMainCadastradoLayout.createSequentialGroup()
                .addGroup(pnlMainCadastradoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlMainCadastradoLayout.createSequentialGroup()
                        .addGap(352, 352, 352)
                        .addGroup(pnlMainCadastradoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnRestaurantesMainCadastrado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnMinhasAvMainCadastrado, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)))
                    .addGroup(pnlMainCadastradoLayout.createSequentialGroup()
                        .addGap(399, 399, 399)
                        .addComponent(btnSairMainCadastrado)))
                .addContainerGap(365, Short.MAX_VALUE))
        );
        pnlMainCadastradoLayout.setVerticalGroup(
            pnlMainCadastradoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMainCadastradoLayout.createSequentialGroup()
                .addGap(189, 189, 189)
                .addComponent(btnRestaurantesMainCadastrado, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnMinhasAvMainCadastrado, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(btnSairMainCadastrado)
                .addContainerGap(235, Short.MAX_VALUE))
        );

        getContentPane().add(pnlMainCadastrado, "card3");

        pnlRestaurantes.setPreferredSize(new java.awt.Dimension(887, 618));

        jLabel3.setText("Buscar Restaurantes");

        btnBuscarRestaurantes.setText("S");

        tblRestaurantes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Restaurante", "Avaliações", "Nota"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.Float.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblRestaurantes);

        btnMeusRestaurantes.setText("MEUS RESTAURANTES");

        btnFazerAvaliacao.setText("FAZER AVALIAÇÃO");

        btnVoltarRestaurantes.setText("VOLTAR");

        javax.swing.GroupLayout pnlRestaurantesLayout = new javax.swing.GroupLayout(pnlRestaurantes);
        pnlRestaurantes.setLayout(pnlRestaurantesLayout);
        pnlRestaurantesLayout.setHorizontalGroup(
            pnlRestaurantesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlRestaurantesLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(btnVoltarRestaurantes)
                .addGap(230, 230, 230)
                .addGroup(pnlRestaurantesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addGroup(pnlRestaurantesLayout.createSequentialGroup()
                        .addComponent(txtBuscaRestaurantes, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnBuscarRestaurantes, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlRestaurantesLayout.createSequentialGroup()
                .addContainerGap(150, Short.MAX_VALUE)
                .addGroup(pnlRestaurantesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 618, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnlRestaurantesLayout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addComponent(btnMeusRestaurantes)
                        .addGap(115, 115, 115)
                        .addComponent(btnFazerAvaliacao)))
                .addGap(119, 119, 119))
        );
        pnlRestaurantesLayout.setVerticalGroup(
            pnlRestaurantesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlRestaurantesLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(pnlRestaurantesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addComponent(btnVoltarRestaurantes, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlRestaurantesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtBuscaRestaurantes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscarRestaurantes))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 388, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(pnlRestaurantesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnMeusRestaurantes, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnFazerAvaliacao, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(62, Short.MAX_VALUE))
        );

        getContentPane().add(pnlRestaurantes, "card4");

        jLabel4.setText("Buscar Restaurante");

        btnBuscarRestVisitante.setText("S");

        tblRestauranteVisitante.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Restaurante", "Avaliações", "Nota"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.Float.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tblRestauranteVisitante);

        btnSairVisitante.setText("SAIR");

        javax.swing.GroupLayout pnlMainVisitanteLayout = new javax.swing.GroupLayout(pnlMainVisitante);
        pnlMainVisitante.setLayout(pnlMainVisitanteLayout);
        pnlMainVisitanteLayout.setHorizontalGroup(
            pnlMainVisitanteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlMainVisitanteLayout.createSequentialGroup()
                .addContainerGap(100, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 678, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(109, 109, 109))
            .addGroup(pnlMainVisitanteLayout.createSequentialGroup()
                .addGroup(pnlMainVisitanteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlMainVisitanteLayout.createSequentialGroup()
                        .addGap(389, 389, 389)
                        .addGroup(pnlMainVisitanteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addGroup(pnlMainVisitanteLayout.createSequentialGroup()
                                .addComponent(txtBuscarRestauranteVisitante, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnBuscarRestVisitante, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(pnlMainVisitanteLayout.createSequentialGroup()
                        .addGap(373, 373, 373)
                        .addComponent(btnSairVisitante, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlMainVisitanteLayout.setVerticalGroup(
            pnlMainVisitanteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMainVisitanteLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlMainVisitanteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtBuscarRestauranteVisitante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscarRestVisitante))
                .addGap(30, 30, 30)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 358, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(btnSairVisitante, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(44, Short.MAX_VALUE))
        );

        getContentPane().add(pnlMainVisitante, "card5");

        tblMinhasAvaliacoes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Restaurante", "Comentário", "Nota"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Float.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tblMinhasAvaliacoes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblMinhasAvaliacoesMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tblMinhasAvaliacoes);

        btnVoltarMinhasAvaliacoes.setText("VOLTAR");
        btnVoltarMinhasAvaliacoes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarMinhasAvaliacoesActionPerformed(evt);
            }
        });

        btnEditarMinhasAvaliacoes.setText("EDITAR");
        btnEditarMinhasAvaliacoes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarMinhasAvaliacoesActionPerformed(evt);
            }
        });

        btnSalvarMinhasAvaliacoes.setText("SALVAR");
        btnSalvarMinhasAvaliacoes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarMinhasAvaliacoesActionPerformed(evt);
            }
        });

        btnExcluirMinhasAvaliacoes.setText("EXCLUIR");
        btnExcluirMinhasAvaliacoes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirMinhasAvaliacoesActionPerformed(evt);
            }
        });

        jLabel5.setText("Comentário");

        txtComentarioMinhasAvaliacoes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtComentarioMinhasAvaliacoesActionPerformed(evt);
            }
        });

        jLabel6.setText("Nota");

        btnBuscarMinhasAvaliacoes.setText("S");

        jLabel7.setText("Buscar Restaurante");

        javax.swing.GroupLayout pnlMinhasAvaliacoesLayout = new javax.swing.GroupLayout(pnlMinhasAvaliacoes);
        pnlMinhasAvaliacoes.setLayout(pnlMinhasAvaliacoesLayout);
        pnlMinhasAvaliacoesLayout.setHorizontalGroup(
            pnlMinhasAvaliacoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMinhasAvaliacoesLayout.createSequentialGroup()
                .addGroup(pnlMinhasAvaliacoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlMinhasAvaliacoesLayout.createSequentialGroup()
                        .addGap(105, 105, 105)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 656, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlMinhasAvaliacoesLayout.createSequentialGroup()
                        .addGap(260, 260, 260)
                        .addGroup(pnlMinhasAvaliacoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlMinhasAvaliacoesLayout.createSequentialGroup()
                                .addComponent(btnEditarMinhasAvaliacoes)
                                .addGap(62, 62, 62)
                                .addComponent(btnSalvarMinhasAvaliacoes)
                                .addGap(68, 68, 68)
                                .addComponent(btnExcluirMinhasAvaliacoes))
                            .addGroup(pnlMinhasAvaliacoesLayout.createSequentialGroup()
                                .addGroup(pnlMinhasAvaliacoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(txtComentarioMinhasAvaliacoes, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(38, 38, 38)
                                .addGroup(pnlMinhasAvaliacoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(txtNotaMinhasAvaliacoes, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(pnlMinhasAvaliacoesLayout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(btnVoltarMinhasAvaliacoes)
                        .addGap(264, 264, 264)
                        .addGroup(pnlMinhasAvaliacoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addGroup(pnlMinhasAvaliacoesLayout.createSequentialGroup()
                                .addComponent(txtBuscarMinhasAvaliacoes, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnBuscarMinhasAvaliacoes, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(126, Short.MAX_VALUE))
        );
        pnlMinhasAvaliacoesLayout.setVerticalGroup(
            pnlMinhasAvaliacoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMinhasAvaliacoesLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(pnlMinhasAvaliacoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnVoltarMinhasAvaliacoes, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlMinhasAvaliacoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtBuscarMinhasAvaliacoes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscarMinhasAvaliacoes))
                .addGap(38, 38, 38)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 339, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(pnlMinhasAvaliacoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlMinhasAvaliacoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtComentarioMinhasAvaliacoes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNotaMinhasAvaliacoes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                .addGroup(pnlMinhasAvaliacoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEditarMinhasAvaliacoes, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSalvarMinhasAvaliacoes, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnExcluirMinhasAvaliacoes, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(56, 56, 56))
        );

        getContentPane().add(pnlMinhasAvaliacoes, "card6");

        tblMeusRestaurantes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Restaurante", "Avaliações", "Nota"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.Float.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane4.setViewportView(tblMeusRestaurantes);

        btnBuscarMeusRestaurantes.setText("S");

        jLabel8.setText("Buscar Restaurante");

        btnCriarRestaurante.setText("CRIAR RESTAURANTE");

        btnVoltarMeusRestaurantes.setText("VOLTAR");

        javax.swing.GroupLayout pnlMeusRestaurantesLayout = new javax.swing.GroupLayout(pnlMeusRestaurantes);
        pnlMeusRestaurantes.setLayout(pnlMeusRestaurantesLayout);
        pnlMeusRestaurantesLayout.setHorizontalGroup(
            pnlMeusRestaurantesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMeusRestaurantesLayout.createSequentialGroup()
                .addGroup(pnlMeusRestaurantesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlMeusRestaurantesLayout.createSequentialGroup()
                        .addGap(153, 153, 153)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 561, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlMeusRestaurantesLayout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(btnVoltarMeusRestaurantes)
                        .addGap(274, 274, 274)
                        .addGroup(pnlMeusRestaurantesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addGroup(pnlMeusRestaurantesLayout.createSequentialGroup()
                                .addComponent(txtBuscarMeusRestaurantes, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnBuscarMeusRestaurantes, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(pnlMeusRestaurantesLayout.createSequentialGroup()
                        .addGap(362, 362, 362)
                        .addComponent(btnCriarRestaurante, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(173, Short.MAX_VALUE))
        );
        pnlMeusRestaurantesLayout.setVerticalGroup(
            pnlMeusRestaurantesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMeusRestaurantesLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(pnlMeusRestaurantesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnVoltarMeusRestaurantes, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlMeusRestaurantesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtBuscarMeusRestaurantes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscarMeusRestaurantes))
                .addGap(44, 44, 44)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 346, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47)
                .addComponent(btnCriarRestaurante, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        getContentPane().add(pnlMeusRestaurantes, "card7");

        tblRestaurantesFazerAvaliacao.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Restaurante"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane5.setViewportView(tblRestaurantesFazerAvaliacao);

        jLabel9.setText("Comentário");

        jLabel10.setText("Nota");

        btnSalvarFazerAvaliacao.setText("SALVAR");

        btnVoltarFazerAvaliacao.setText("VOLTAR");

        btnBuscarFazerAvaliacao.setText("S");

        jLabel11.setText("Buscar Restaurante");

        javax.swing.GroupLayout pnlFazerAvaliacaoLayout = new javax.swing.GroupLayout(pnlFazerAvaliacao);
        pnlFazerAvaliacao.setLayout(pnlFazerAvaliacaoLayout);
        pnlFazerAvaliacaoLayout.setHorizontalGroup(
            pnlFazerAvaliacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlFazerAvaliacaoLayout.createSequentialGroup()
                .addContainerGap(221, Short.MAX_VALUE)
                .addGroup(pnlFazerAvaliacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlFazerAvaliacaoLayout.createSequentialGroup()
                        .addGroup(pnlFazerAvaliacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(pnlFazerAvaliacaoLayout.createSequentialGroup()
                                .addGroup(pnlFazerAvaliacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(pnlFazerAvaliacaoLayout.createSequentialGroup()
                                        .addComponent(txtComentarioFazerAvaliacao)
                                        .addGap(32, 32, 32))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlFazerAvaliacaoLayout.createSequentialGroup()
                                        .addComponent(jLabel9)
                                        .addGap(338, 338, 338)))
                                .addGroup(pnlFazerAvaliacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel10)
                                    .addComponent(txtNotaFazerAvaliacao, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(214, 214, 214))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlFazerAvaliacaoLayout.createSequentialGroup()
                        .addComponent(btnSalvarFazerAvaliacao, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(376, 376, 376))))
            .addGroup(pnlFazerAvaliacaoLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(btnVoltarFazerAvaliacao)
                .addGap(289, 289, 289)
                .addGroup(pnlFazerAvaliacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlFazerAvaliacaoLayout.createSequentialGroup()
                        .addComponent(txtBuscarFazerAvaliacao, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnBuscarFazerAvaliacao, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel11))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        pnlFazerAvaliacaoLayout.setVerticalGroup(
            pnlFazerAvaliacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlFazerAvaliacaoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlFazerAvaliacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlFazerAvaliacaoLayout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlFazerAvaliacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtBuscarFazerAvaliacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnBuscarFazerAvaliacao)))
                    .addComponent(btnVoltarFazerAvaliacao, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlFazerAvaliacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10))
                .addGap(5, 5, 5)
                .addGroup(pnlFazerAvaliacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtComentarioFazerAvaliacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNotaFazerAvaliacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(52, 52, 52)
                .addComponent(btnSalvarFazerAvaliacao, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32))
        );

        getContentPane().add(pnlFazerAvaliacao, "card8");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtUsuarioLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsuarioLoginActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUsuarioLoginActionPerformed

    private void btnRestaurantesMainCadastradoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRestaurantesMainCadastradoActionPerformed
        // TODO add your handling code here:
        pnlLogin.setVisible(false);
        pnlMainCadastrado.setVisible(false);
        pnlRestaurantes.setVisible(true);
        pnlMainVisitante.setVisible(false);
        pnlMinhasAvaliacoes.setVisible(false);
        pnlMeusRestaurantes.setVisible(false);
        pnlFazerAvaliacao.setVisible(false);
    }//GEN-LAST:event_btnRestaurantesMainCadastradoActionPerformed

    private void txtComentarioMinhasAvaliacoesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtComentarioMinhasAvaliacoesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtComentarioMinhasAvaliacoesActionPerformed

    private void btnAcessarLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAcessarLoginActionPerformed
        //==============================NICOLAS
        String usuario = txtUsuarioLogin.getText();
        String senha = txtSenhaLogin.getText();
        
        Usuario usuarioEncontrado = Usuario.getListaUsuarios().stream()
            .filter(u -> u.getUsuario().equals(usuario))
            .findFirst()
            .orElse(null);
        
        if (usuarioEncontrado != null) {
            if (usuarioEncontrado.getSenha().equals(senha)){
                
                usuarioAtual = usuarioEncontrado;
                pnlLogin.setVisible(false);
                pnlMainCadastrado.setVisible(true);
                pnlRestaurantes.setVisible(false);
                pnlMainVisitante.setVisible(false);
                pnlMinhasAvaliacoes.setVisible(false);
                pnlMeusRestaurantes.setVisible(false);
                pnlFazerAvaliacao.setVisible(false);
            }
            else{
                JOptionPane.showMessageDialog(null, "Senha informada está incorreta.", "Erro", JOptionPane.ERROR_MESSAGE);
                pnlLogin.setVisible(true);
                pnlMainCadastrado.setVisible(false);
                pnlRestaurantes.setVisible(false);
                pnlMainVisitante.setVisible(false);
                pnlMinhasAvaliacoes.setVisible(false);
                pnlMeusRestaurantes.setVisible(false);
                pnlFazerAvaliacao.setVisible(false);
            }
        } else {
            JOptionPane.showMessageDialog(null, "Usuário informado não existe.", "Erro", JOptionPane.ERROR_MESSAGE);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAcessarLoginActionPerformed

    private void btnCriarContaLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCriarContaLoginActionPerformed
        // TODO add your handling code here:
        TelaCriarConta telaCriarConta = new TelaCriarConta();
        telaCriarConta.setVisible(true);
    }//GEN-LAST:event_btnCriarContaLoginActionPerformed

    private void btnEntrarVisitanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEntrarVisitanteActionPerformed
        // TODO add your handling code here:
        pnlLogin.setVisible(false);
        pnlMainCadastrado.setVisible(false);
        pnlRestaurantes.setVisible(false);
        pnlMainVisitante.setVisible(true);
        pnlMinhasAvaliacoes.setVisible(false);
        pnlMeusRestaurantes.setVisible(false);
        pnlFazerAvaliacao.setVisible(false);
    }//GEN-LAST:event_btnEntrarVisitanteActionPerformed

    private void btnMinhasAvMainCadastradoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMinhasAvMainCadastradoActionPerformed
        // TODO add your handling code here:
        
        pnlLogin.setVisible(false);
        pnlMainCadastrado.setVisible(false);
        pnlRestaurantes.setVisible(false);
        pnlMainVisitante.setVisible(false);
        pnlMinhasAvaliacoes.setVisible(true);
        pnlMeusRestaurantes.setVisible(false);
        pnlFazerAvaliacao.setVisible(false);
        carregarTblMinhasAvaliacoes(usuarioAtual);
        
        btnExcluirMinhasAvaliacoes.setEnabled(false);
        btnSalvarMinhasAvaliacoes.setEnabled(false);
        btnEditarMinhasAvaliacoes.setEnabled(false);
        txtComentarioMinhasAvaliacoes.setEnabled(false);
        txtNotaMinhasAvaliacoes.setEnabled(false);
    }//GEN-LAST:event_btnMinhasAvMainCadastradoActionPerformed

    private void btnSairMainCadastradoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairMainCadastradoActionPerformed
        // TODO add your handling code here:
        usuarioAtual = null;
        pnlLogin.setVisible(true);
        pnlMainCadastrado.setVisible(false);
        pnlRestaurantes.setVisible(false);
        pnlMainVisitante.setVisible(false);
        pnlMinhasAvaliacoes.setVisible(false);
        pnlMeusRestaurantes.setVisible(false);
        pnlFazerAvaliacao.setVisible(false);
        
        txtUsuarioLogin.setText("");
        txtSenhaLogin.setText("");
    }//GEN-LAST:event_btnSairMainCadastradoActionPerformed

    private void btnSalvarMinhasAvaliacoesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarMinhasAvaliacoesActionPerformed
        // TODO add your handling code here:
        btnExcluirMinhasAvaliacoes.setEnabled(false);
        btnSalvarMinhasAvaliacoes.setEnabled(false);
        btnEditarMinhasAvaliacoes.setEnabled(false);
        txtComentarioMinhasAvaliacoes.setEnabled(false);
        txtNotaMinhasAvaliacoes.setEnabled(false);
        
        int index = tblMinhasAvaliacoes.getSelectedRow();
        usuarioAtual.getListaAvaliacoes().get(index).setConteudo(txtComentarioMinhasAvaliacoes.getText());
        usuarioAtual.getListaAvaliacoes().get(index).setNota(Float.parseFloat(txtNotaMinhasAvaliacoes.getText()));
        
        carregarTblMinhasAvaliacoes(usuarioAtual);
    }//GEN-LAST:event_btnSalvarMinhasAvaliacoesActionPerformed

    private void btnVoltarMinhasAvaliacoesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarMinhasAvaliacoesActionPerformed
        // TODO add your handling code here:
        pnlLogin.setVisible(false);
        pnlMainCadastrado.setVisible(true);
        pnlRestaurantes.setVisible(false);
        pnlMainVisitante.setVisible(false);
        pnlMinhasAvaliacoes.setVisible(false);
        pnlMeusRestaurantes.setVisible(false);
        pnlFazerAvaliacao.setVisible(false);
        txtComentarioMinhasAvaliacoes.setText("");
        txtNotaMinhasAvaliacoes.setText("");
    }//GEN-LAST:event_btnVoltarMinhasAvaliacoesActionPerformed

    private void tblMinhasAvaliacoesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblMinhasAvaliacoesMouseClicked
        // TODO add your handling code here:
        
        btnExcluirMinhasAvaliacoes.setEnabled(true);
        btnSalvarMinhasAvaliacoes.setEnabled(false);
        btnEditarMinhasAvaliacoes.setEnabled(true);
        txtComentarioMinhasAvaliacoes.setEnabled(false);
        txtNotaMinhasAvaliacoes.setEnabled(false);
        
        int i = tblMinhasAvaliacoes.getSelectedRow();
        if(i>=0 && i<usuarioAtual.getListaAvaliacoes().size()){
            Avaliacao avaliacao = usuarioAtual.getListaAvaliacoes().get(i);
            txtComentarioMinhasAvaliacoes.setText(avaliacao.getConteudo());
            txtNotaMinhasAvaliacoes.setText(Float.toString(avaliacao.getNota()));
            
        }
        
        
    }//GEN-LAST:event_tblMinhasAvaliacoesMouseClicked

    private void btnEditarMinhasAvaliacoesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarMinhasAvaliacoesActionPerformed
        // TODO add your handling code here:
        btnExcluirMinhasAvaliacoes.setEnabled(false);
        btnSalvarMinhasAvaliacoes.setEnabled(true);
        btnEditarMinhasAvaliacoes.setEnabled(false);
        txtComentarioMinhasAvaliacoes.setEnabled(true);
        txtNotaMinhasAvaliacoes.setEnabled(true);
        
    }//GEN-LAST:event_btnEditarMinhasAvaliacoesActionPerformed

    private void btnExcluirMinhasAvaliacoesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirMinhasAvaliacoesActionPerformed
        // TODO add your handling code here:
        int i = tblMinhasAvaliacoes.getSelectedRow();
                
        if(i>=0 && i<usuarioAtual.getListaAvaliacoes().size()){
            int opcaoSelecionada = JOptionPane.showConfirmDialog(null, "Deseja remover a avaliação selecionada?", "Confirmação de Remoção", JOptionPane.YES_NO_OPTION);
            if(opcaoSelecionada == JOptionPane.YES_OPTION){
                Avaliacao removida = usuarioAtual.getListaAvaliacoes().get(i);
                usuarioAtual.getListaAvaliacoes().remove(removida);
            }
        }
        
        btnExcluirMinhasAvaliacoes.setEnabled(false);
        btnSalvarMinhasAvaliacoes.setEnabled(false);
        btnEditarMinhasAvaliacoes.setEnabled(false);
        txtComentarioMinhasAvaliacoes.setEnabled(false);
        txtNotaMinhasAvaliacoes.setEnabled(false);
        txtComentarioMinhasAvaliacoes.setText("");
        txtNotaMinhasAvaliacoes.setText("");
        
        carregarTblMinhasAvaliacoes(usuarioAtual);
    }//GEN-LAST:event_btnExcluirMinhasAvaliacoesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAcessarLogin;
    private javax.swing.JButton btnBuscarFazerAvaliacao;
    private javax.swing.JButton btnBuscarMeusRestaurantes;
    private javax.swing.JButton btnBuscarMinhasAvaliacoes;
    private javax.swing.JButton btnBuscarRestVisitante;
    private javax.swing.JButton btnBuscarRestaurantes;
    private javax.swing.JButton btnCriarContaLogin;
    private javax.swing.JButton btnCriarRestaurante;
    private javax.swing.JButton btnEditarMinhasAvaliacoes;
    private javax.swing.JButton btnEntrarVisitante;
    private javax.swing.JButton btnExcluirMinhasAvaliacoes;
    private javax.swing.JButton btnFazerAvaliacao;
    private javax.swing.JButton btnMeusRestaurantes;
    private javax.swing.JButton btnMinhasAvMainCadastrado;
    private javax.swing.JButton btnRestaurantesMainCadastrado;
    private javax.swing.JButton btnSairMainCadastrado;
    private javax.swing.JButton btnSairVisitante;
    private javax.swing.JButton btnSalvarFazerAvaliacao;
    private javax.swing.JButton btnSalvarMinhasAvaliacoes;
    private javax.swing.JButton btnVoltarFazerAvaliacao;
    private javax.swing.JButton btnVoltarMeusRestaurantes;
    private javax.swing.JButton btnVoltarMinhasAvaliacoes;
    private javax.swing.JButton btnVoltarRestaurantes;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JPanel pnlFazerAvaliacao;
    private javax.swing.JPanel pnlLogin;
    private javax.swing.JPanel pnlMainCadastrado;
    private javax.swing.JPanel pnlMainVisitante;
    private javax.swing.JPanel pnlMeusRestaurantes;
    private javax.swing.JPanel pnlMinhasAvaliacoes;
    private javax.swing.JPanel pnlRestaurantes;
    private javax.swing.JTable tblMeusRestaurantes;
    private javax.swing.JTable tblMinhasAvaliacoes;
    private javax.swing.JTable tblRestauranteVisitante;
    private javax.swing.JTable tblRestaurantes;
    private javax.swing.JTable tblRestaurantesFazerAvaliacao;
    private javax.swing.JTextField txtBuscaRestaurantes;
    private javax.swing.JTextField txtBuscarFazerAvaliacao;
    private javax.swing.JTextField txtBuscarMeusRestaurantes;
    private javax.swing.JTextField txtBuscarMinhasAvaliacoes;
    private javax.swing.JTextField txtBuscarRestauranteVisitante;
    private javax.swing.JTextField txtComentarioFazerAvaliacao;
    private javax.swing.JTextField txtComentarioMinhasAvaliacoes;
    private javax.swing.JTextField txtNotaFazerAvaliacao;
    private javax.swing.JTextField txtNotaMinhasAvaliacoes;
    private javax.swing.JPasswordField txtSenhaLogin;
    private javax.swing.JTextField txtUsuarioLogin;
    // End of variables declaration//GEN-END:variables
}
