/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package telas;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
import modelos.Avaliacao;
import modelos.Usuario;
import modelos.Restaurante;
import permanencia.interfaces.AvaliacaoDAO;
import servicos.ServicoAvaliacao;
import permanencia.interfaces.UsuarioDAO;
import servicos.ServicoUsuario;
import permanencia.interfaces.RestauranteDAO;
import servicos.ServicoRestaurante;


/**
 *
 * @author Nicopau
 */
public class TelaVisualizarAvaliacoes extends javax.swing.JFrame {

    /**
     * Creates new form TelaVisualizarAvaliacoes
     */
    private ArrayList<Avaliacao> listAvaliacoes = new ArrayList();
    private String nomerestaurante = "Restaurante";
    private int idrestaurante = -1;
    private Restaurante rest;
    public TelaVisualizarAvaliacoes(Restaurante restaurante) {
        rest = restaurante;
        nomerestaurante = restaurante.getNome();
        idrestaurante = restaurante.getIdRestaurante();
        initComponents();
        lbl_nomeres.setText(nomerestaurante);
        ArrayList<Avaliacao> templist = ServicoAvaliacao.buscaTodos();
        int i = 0;
        int limit = templist.size();
        while(i < limit) {
            Avaliacao ava = templist.get(i);
            if (ava.getIdRestaurante() == idrestaurante) {
                listAvaliacoes.add(ava);
            }
            i = i +1;
        }
        carregarTabelaAvaliacoes();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblAva = new javax.swing.JTable();
        lblNomeRestauranteVisualizarMenu = new javax.swing.JLabel();
        lbl_nomeres = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tblAva.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Usuário", "Comentário", "Nota"
            }
        ));
        jScrollPane1.setViewportView(tblAva);

        lblNomeRestauranteVisualizarMenu.setText("Avaliações");

        lbl_nomeres.setText("AVA");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(lblNomeRestauranteVisualizarMenu)
                        .addGap(18, 18, 18)
                        .addComponent(lbl_nomeres)))
                .addContainerGap(57, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(13, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNomeRestauranteVisualizarMenu)
                    .addComponent(lbl_nomeres))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 391, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaVisualizarAvaliacoes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaVisualizarAvaliacoes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaVisualizarAvaliacoes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaVisualizarAvaliacoes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Restaurante testerest = ServicoRestaurante.buscarPorId(0);
                if (testerest == null) {
                    testerest = new Restaurante(0,-1,"Teste","TESTE","NADA",false);
                }
                new TelaVisualizarAvaliacoes(testerest).setVisible(true);
            }
        });
    }
    
public void carregarTabelaAvaliacoes() {
        DefaultTableModel modeloAvas = new DefaultTableModel(new Object[] {"Prato","Descrição","Preço"},0);
        for (int i=0;i<listAvaliacoes.size();i++) {
            Avaliacao avaliacao = listAvaliacoes.get(i);
            int userid = avaliacao.getIdUsuario();
            Usuario user = ServicoUsuario.buscarPorId(userid);
            Object linha[];
            if (user == null) {
                linha = new Object[]{"TESTE", 
                avaliacao.getConteudo(), avaliacao.getNota()
                };
            }
            else {
                linha = new Object[]{user.getNome(), 
                avaliacao.getConteudo(), avaliacao.getNota()
                };
            }
            modeloAvas.addRow(linha);
        }
        tblAva.setModel(modeloAvas);
        tblAva.setDefaultEditor(Object.class, null);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblNomeRestauranteVisualizarMenu;
    private javax.swing.JLabel lbl_nomeres;
    private javax.swing.JTable tblAva;
    // End of variables declaration//GEN-END:variables
}
