/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package telas;

import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
import modelos.Prato;
import modelos.Restaurante;
import permanencia.interfaces.PratoDAO;
import servicos.ServicoPrato;
import permanencia.interfaces.RestauranteDAO;
import servicos.ServicoRestaurante;

/**
 *
 * @author Nicopau
 */
public class TelaVisualizarMenu extends javax.swing.JFrame {

    /**
     * Creates new form TelaVisualizarMenu
     */
    private ArrayList<Prato> listPratos = new ArrayList();
    private String nomerestaurante = "Restaurante";
    private int idrestaurante = -1;
    private Restaurante rest;
    public TelaVisualizarMenu(Restaurante restaurante) {
        rest = restaurante;
        nomerestaurante = restaurante.getNome();
        idrestaurante = restaurante.getIdRestaurante();
        initComponents();
        lbl_nomeres.setText(nomerestaurante);
        ArrayList<Prato> templist = ServicoPrato.buscaTodos();
        int i = 0;
        int limit = templist.size();
        while(i < limit) {
            Prato prt = templist.get(i);
            if (prt.getIdRestaurante() == idrestaurante) {
                listPratos.add(prt);
            }
            i = i +1;
        }
        carregarTabelaPratos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblPratos = new javax.swing.JTable();
        lblNomeRestauranteVisualizarMenu = new javax.swing.JLabel();
        lbl_nomeres = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tblPratos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Prato", "Descrição", "Preço"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblPratos);

        lblNomeRestauranteVisualizarMenu.setText("Menu");

        lbl_nomeres.setText("RESTAURANTE");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblNomeRestauranteVisualizarMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbl_nomeres)))
                .addContainerGap(73, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNomeRestauranteVisualizarMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_nomeres))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 379, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(33, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaVisualizarMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaVisualizarMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaVisualizarMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaVisualizarMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Restaurante testerest = ServicoRestaurante.buscarPorId(0);
                if (testerest == null) {
                    testerest = new Restaurante(0,-1,"Teste","TESTE","NADA",false);
                }
                new TelaVisualizarMenu(testerest).setVisible(true);
            }
        });
    }
    
    public void carregarTabelaPratos() {
        DefaultTableModel modeloPratos = new DefaultTableModel(new Object[] {"Prato","Descrição","Preço"},0);
        for (int i=0;i<listPratos.size();i++) {
            Prato prato = listPratos.get(i);
            Object linha[] = new Object[]{prato.getNome(), 
                prato.getDescricao(), String.format("%.2f",prato.getPreco()).replace(",", ".")
            };
            modeloPratos.addRow(linha);
        }
        tblPratos.setModel(modeloPratos);
        tblPratos.setDefaultEditor(Object.class, null);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblNomeRestauranteVisualizarMenu;
    private javax.swing.JLabel lbl_nomeres;
    private javax.swing.JTable tblPratos;
    // End of variables declaration//GEN-END:variables
}
